# Generated by Django 4.1.2 on 2024-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistente',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='asistente',
            name='apellidos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='apellidos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
