# Generated by Django 4.1.2 on 2024-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'doctor'), (2, 'Administrador')], default=1),
        ),
    ]
