# Generated by Django 4.1.2 on 2024-02-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_alter_asistente_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='celular',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='domicilio',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='celular',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='domicilio',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
