# Generated by Django 4.1.2 on 2024-06-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_doctor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Doctor'), (2, 'Administrador')], default=1),
        ),
    ]
