# Generated by Django 4.1.2 on 2024-06-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Asistente'), (2, 'Administrador')], default=1),
        ),
    ]
