# Generated by Django 4.1.2 on 2024-06-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fechaHoraCita', models.DateTimeField()),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Confirmado'), (3, 'Atendiendo'), (4, 'Finalizado'), (5, 'Validado'), (6, 'Cancelado')])),
                ('tipo', models.IntegerField(choices=[(1, 'Tentativa'), (2, 'Agil'), (3, 'Completa'), (4, 'Ocupado')])),
                ('razon', models.CharField(max_length=200, null=True)),
                ('razonOcupado', models.CharField(blank=True, max_length=100, null=True)),
                ('datosPaciente', models.CharField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True)),
                ('fechaConfirmacion', models.DateTimeField(blank=True, help_text='Fecha en que se confirmó la cita.', null=True)),
                ('fechaValidacion', models.DateTimeField(blank=True, help_text='Fecha en que se validó la cita.', null=True)),
                ('fechaInicio', models.DateTimeField(blank=True, help_text='Fecha de inicio de la cita.', null=True)),
                ('fechaFin', models.DateTimeField(blank=True, help_text='Fecha de finalización de la cita.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
