# Generated by Django 4.1.2 on 2024-06-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('motivoConsulta', models.CharField(max_length=60)),
                ('examenInterior', models.CharField(max_length=60)),
                ('examenExterior', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
