# Generated by Django 4.1.2 on 2023-09-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0003_alter_historiaclinica_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='examenExterior',
            field=models.CharField(default='ds', max_length=60),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='examenInterior',
            field=models.CharField(default='d', max_length=60),
        ),
    ]
