# Generated by Django 4.1.2 on 2023-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0004_historiaclinica_examenexterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='examenExterior',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='examenInterior',
            field=models.CharField(max_length=60),
        ),
    ]
